let result = await Promise.reject('Failure').catch(console.log)